project_id = "graluwrigdryungsfwfw"

# Edge Functions Configuration
# Environment variables should be set via Supabase Dashboard or CLI
# Required: GEMINI_API_KEY for generate-ai-caption function

[functions.fetch-youtube-video]
verify_jwt = true

[functions.generate-ai-caption]
verify_jwt = true